name: "\U0001F30F Environment"
description: "ì¶”ê°€ì ì¸ í™˜ê²½ì„¤ì •ì´ í•„ìš”í•œê°€ìš”?"
labels: "\U0001F30F Environment"
body:
  - type: textarea
    attributes:
      label: ğŸ¤” Describe
      description: í˜„ì¬ ì–´ë–¤ ìƒí™©ì¸ì§€ ì„¤ëª…í•´ ì£¼ì„¸ìš”.
      placeholder: ìì„¸íˆ ì ì„ìˆ˜ë¡ ì¢‹ìŠµë‹ˆë‹¤!
    validations:
      required: true
  - type: textarea
    attributes:
      label: âœ… Tasks
      description: ì¶”ê°€í•  í™˜ê²½ ì„¤ì •ì— ëŒ€í•´ ê°„ëµíˆ ê¸°ë¡í•´ ì£¼ì„¸ìš”.
      placeholder: ìµœëŒ€í•œ ì„¸ë¶„í™” í•´ì„œ ì ì–´ì£¼ì„¸ìš”!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸ™‹ğŸ» More
      description: ë” í•˜ê³  ì‹¶ì€ ë§ì´ ìˆë‹¤ë©´ ì‘ì„±í•´ ì£¼ì„¸ìš”.
